version: '3.9'

services:
  san_bot:
    build:
      context: .
      # Не указываем target: builder, чтобы Dockerfile собрался целиком
      # (Если у вас во втором FROM есть 'AS final', можно прописать 'target: final')

    container_name: san_bot_container

    # Передаём секреты и настройки в контейнер через .env-файл
    env_file:
      - .env

    # Можно дополнительно продублировать важные переменные:
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1

    # Пробрасываем локальные папки в контейнер
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    # Контейнер будет перезапускаться, если упадёт
    restart: unless-stopped

    # Подключаем к сети (обязательно без internal: true, чтобы был доступ к Интернету)
    networks:
      - bot_network

    # Healthcheck для проверки, что бот действительно работает
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python -u bot.py' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  bot_network:
    driver: bridge
    # internal: true  # НЕ устанавливайте, если нужен выход в Интернет/Telegram
