version: "3.9"

services:
  san_bot:
    build:
      context: .
      # Не указываем target: builder — иначе соберётся только промежуточный слой
    container_name: san_bot_container

    # Передаём переменные окружения из .env
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      PYTHONUNBUFFERED: 1

    # Пробрасываем локальные папки data/ и logs/ в контейнер
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    # Контейнер будет перезапускаться, если упадёт
    restart: unless-stopped

    # Сеть для бота (по желанию)
    networks:
      - bot_network

    # Проверка, что бот жив
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python -u bot.py' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  bot_network:
    driver: bridge
    # internal: true  # НЕ устанавливаем, чтобы был доступ в интернет
